config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  resources :posts do
    resources :comments
  end

  root "posts#index"

  get '/about', to: 'pages#about'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class: 'User', foreign_key: 'user_id'

  has_many :comments, dependent: :destroy
  has_many :post_tags
  has_many :tags, through: :post_tags


  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true

  def tag_ids=(ids)
    ids.each do |id|
      if !id.empty?
        selected_tag = Tag.find(id)
        self.tags << selected_tag unless self.tags.include? selected_tag
      end
    end
  end

  def tags_attributes=(tag_attributes)
    if !tag_attributes.empty? && tag_attributes != ''
      tag = Tag.find_or_create_by(tag_attributes)
      self.tags << tag unless self.tags.include? tag
    end
  end

end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :post_tags
  has_many :posts, through: :post_tags

  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end
  
end

app/controllers/posts_controller.rb
require 'pry'
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private

    def post_params
      params.require(:post).permit(:title, :body, tag_ids: [], tags_attributes: [:name])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class='comment_name'><strong><%= comment.name %></strong></p>
    <p class='comment_body'><%= comment.body %></p>
    <p class='comment_time'>Commited Created on: <%= @post.created_at.strftime("%B, %d, %Y") %><% if user_signed_in? %> | <%= link_to 'Delete', [comment.post, comment], method: :delete, class: 'button', data: { confirm: 'Are you sure?' } %><% end %></p>
  </div>

</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control" %>
  </p><br>

  <p>
    <%= f.submit 'Add Comment', class: 'btn btn-default btn-primary' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Words</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>
  <!-- NavBar -->
  <div class="hero hero-with-image hero-with-pulled-image">
    <header id='main-nav' class='nav'>
      <div class="container">
        <div class="header-content">
          <div class="logo-and-title">
            <%= link_to root_path do %>
              <%= image_tag 'white-logo.png', class: 'logo' %>
            <% end %>
          </div>
          <nav>
            <%= link_to 'About', about_path %>
            <% if !user_signed_in? %>
              <%= link_to 'Log In', new_user_session_path %></p>
            <% end %>

            <% if user_signed_in? %>
                <%= link_to 'New Post', new_post_path %>
                <%= link_to 'Log Out', destroy_user_session_path, :method => :delete %>
            <% end %>
          </nav>
        </div>
      </div>
    </header>
  </div>

  <!-- end of header -->

  <div class="background-image" style="background-image: url(/assets/background.jpg);">
  </div>

  <div class="container-fluid top-view">
    <div class="center-white">
      <h1>Welcome To Words</h1>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      </p>
    </div>
  </div>

  <div class=main-content>
    <% if current_page?(root_path) %>
      <p>All Posts</p>
    <% elsif current_page?(about_path) %>
      <p>About</p>
    <% else %>
      <%= link_to 'See All Posts', root_path %>
    <% end %>



    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: 'alert') %>
    <% end %>

      <%= yield %>


  </div> <!-- end of main-content div -->

</body>
</html>

app/views/pages/about.html.erb
<div id='about'>
  <h1>Words</h1>
  <h3>About:</h3>
  <p>Welcome to Words! Words was created, so that Learn Verified students had a resource to post the blogs they need to write in the Learn Verified program. We hope to deploy this site online soon, so that all students can access this program.
  </p>
  <p>This site is an open source project. Please feel free to contribute to my site &#64; <a href='https://github.com/Lukeghenco/words'>GitHub</a>.</p>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id='errors'>
      <h2><%= pluralize(@post.errors.count, 'error') %> errors need to be fixed before we can save your post!</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>

    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control" %>

    <%= f.label('New Tag Name') %>

    <%= text_field_tag 'post[tags_attributes[name]]', "", class: 'form-control'%>


    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name, :inline => true %><br>

  <%= f.submit 'Create Post', class: 'btn btn-default btn-primary' %>

<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Your Post</h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <h2 class='title'><%= link_to post.title, post %></h2>
    <p class='date'><%= post.created_at.strftime("%B, %d, %Y") %></p>
    <div id="tags">
        Tags: <% post.tags.uniq.each do |tag| %>
          <% if tag.name != "" && tag.name != nil %>
             <%= tag.name %>
          <% end %>
        <% end %>
    </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>New Post</h1>

  <%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
      <div id='errors'>
        <h2><%= pluralize(@post.errors.count, 'error') %> erros need to be fixed before we can save your post!</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>

      </div>

    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %>
    </p>

  <% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class='title'>
    <%= @post.title %>
  </h1>

  <p class='date'>
    Submitted on: <%= @post.created_at.strftime("%B, %d, %Y") %>
    <% if user_signed_in? %>
      | <%= link_to 'Edit', edit_post_path(@post)%>
      | <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>

  <p class='body'>
    <%= @post.body %>
  </p>

  <div id='comments'>
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>

    <h3>Add a comment:</h3>
    <%= render 'comments/form' %>

  </div>

  <div id="tags">
    <ul>
      <% @post.tags.each do |tag| %>
        <li><%= tag.name %></li>
      <% end %>
    </ul>
  </div>
</div>